### ISSUE TITLE
Previous video keeps showing after new one is opened

### ISSUE THREAD

**Issue by OrcaXS** [Kagami/boram#26] opened 2018-01-30 06:20 UTC
* Open a video file
* Close the only tab and open a new video file
* Still shows the previous video

Platform: macOS 10.13.3
Built from source 4a8cba55d80866ffd29202c7490c2dd213d1b685
Since there's currently no building instructions I figured out the following one.
(NaCl SDK installed and configured following https://github.com/Kagami/mpv.js)

```bash
yarn
./scripts/make-mac64-deps.sh
mkdir bin/mac64
cp -a scripts/dist/* bin/mac64/
yarn app
cp -a build/Release/boram.node dist/app/libboram.dylib
yarn dev
```

**Comment by Kagami** [comment] 2018-01-30 10:22
Can you reproduce it with latest [release build](https://github.com/Kagami/boram/releases/tag/v0.3.7)?

**Comment by OrcaXS** [comment] 2018-01-30 10:28
No, the problem only exists when building from source. Looks fine in release build.
Is there any problem with my building process?

**Comment by Kagami** [comment] 2018-01-30 11:27
This might be because of updated mpv version. Please try

```
brew install mpv@0.27.0
cp /usr/local/lib/libmpv.1.dylib bin/mac64
```

**Comment by OrcaXS** [comment] 2018-01-30 12:51
I tried https://github.com/Homebrew/homebrew-core/commit/1fd000f75cf53b9fef25eb447117e552fbd16bf8 because I can't install older version via `brew install mpv@0.27.0`. No luck.

But this time I checked console, following errors were logged when closing the tab. 
Closing the tab wasn't really closing the video, the audio was still playing.

![image](https://user-images.githubusercontent.com/1764123/35566875-f1044f3c-05fd-11e8-9289-7188d80937b0.png)

**Comment by Kagami** [comment] 2018-01-30 12:56
Ok, I will test build with latest mpv on Mac OS then.

**Comment by Kagami** [comment] 2018-07-23 08:52
Just build boram v0.4.0-dev with mpv 0.29.0, seems fine to me.
Except that if I open two videos, set to pause and switch between them, stop-frame is not updated. But that seems to be old issue.

**Comment by Kagami** [comment] 2018-07-26 07:01
Closing for now. Let me know if the problem still remains.

**Closed by Kagami** 2018-07-26 07:01 UTC
